參考資料：

https://ithelp.ithome.com.tw/articles/10209593

http://alrightchiu.github.io/SecondRound/single-source-shortest-pathdijkstras-algorithm.html

http://nthucad.cs.nthu.edu.tw/~yyliu/personal/nou/04ds/dijkstra.html

https://www.youtube.com/watch?v=9wV1VxlfBlI

https://www.youtube.com/watch?v=pVfj6mxhdMw&t

https://www.geeksforgeeks.org/kruskals-minimum-spanning-tree-algorithm-greedy-algo-2/

https://www.youtube.com/watch?v=71UQH7Pr9kU

http://alrightchiu.github.io/SecondRound/minimum-spanning-treeintrojian-jie.html

那個Kruskal演算法是用來算"Minmum Spanning Tree"

然後Dijkstra演算法是用來算"Shortest Path"

12/20先來研究助教給的測值，那個矩陣就是用來創建Graph用的，每個點能連到的點，跟其距離

然後addEdge依序輸入的變數代表"起點"、"終點"、"權重" 

In [32]:
from collections import defaultdict
import numpy as np

class Graph(): 

    def __init__(self, vertices): 
        self.V = vertices 
        self.graph = [] 
        self.graph_matrix = [[0 for column in range(vertices)]
                    for row in range(vertices)] 
    
    def addEdge(self,u,v,w): 
        """
        :type u,v,w: int
        :rtype: None
        """
    def Dijkstra(self, s): 
        """
        :type s: int
        :rtype: dict
        """
    def Kruskal(self):
        """
        :rtype: dict
        """
    
    def printt(self):
        print(np.matrix(self.graph_matrix))

In [33]:
Graph(9).printt() #由於print出來的矩陣很醜，所以我先import numpy套件

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [34]:
a = Graph(9)
a.graph#恩，原來可以用這樣的方式來呼叫init裡面的變數

[]

In [36]:
a.V#恩，原來可以用這樣的方式來呼叫init裡面的變數

9

In [5]:
from collections import defaultdict
import numpy as np

class Graph(): 

    def __init__(self, vertices): 
        self.V = vertices 
        self.graph = [] 
        self.graph_matrix = [[0 for column in range(vertices)]
                    for row in range(vertices)] 
    
    def addEdge(self,u,v,w): 
        """
        :type u,v,w: int
        :rtype: None
        """
    def Dijkstra(self, s): 
        for i in range(self.V):
            for j in range(self.V):
                if i == 0:
                    self.graph_matrix[i][j] = self.graph[i][j]
        print(np.matrix(self.graph_matrix))
        
    def Kruskal(self):
        """
        :rtype: dict
        """

In [7]:
a = Graph(9)
a.graph =  [[0,4,0,0,0,0,0,8,0],
            [4,8,0,0,0,0,0,11,0],
            [0,8,0,7,0,4,0,0,2],
            [0,0,7,0,9,14,0,0,0],
            [0,0,0,9,0,10,0,0,0],
            [0,0,4,14,10,0,2,0,0],
            [0,0,0,0,0,2,0,1,6],
            [8,11,0,0,0,0,1,0,7],
            [0,0,2,0,0,0,6,7,0]]
a.Dijkstra(0)

[[0 4 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [8]:
from collections import defaultdict
import numpy as np

class Graph(): 

    def __init__(self, vertices): 
        self.V = vertices 
        self.graph = [] 
        self.graph_matrix = [[0 for column in range(vertices)]
                    for row in range(vertices)] 
    
    def addEdge(self,u,v,w): 
        """
        :type u,v,w: int
        :rtype: None
        """
    def Dijkstra(self, s):
        self.graph_matrix[0] = self.graph[s]
        path = [s]
        
        for i in range(self.V):
            for j in range(self.V):
                if self.graph[i][j] != 0:
                    print(i,j)
                
                
                    
        print(np.matrix(self.graph_matrix))
        
    def Kruskal(self):
        """
        :rtype: dict
        """

In [10]:
a = Graph(9)
a.graph =  [[0,4,0,0,0,0,0,8,0],
            [4,0,8,0,0,0,0,11,0],
            [0,8,0,7,0,4,0,0,2],
            [0,0,7,0,9,14,0,0,0],
            [0,0,0,9,0,10,0,0,0],
            [0,0,4,14,10,0,2,0,0],
            [0,0,0,0,0,2,0,1,6],
            [8,11,0,0,0,0,1,0,7],
            [0,0,2,0,0,0,6,7,0]]
a.Dijkstra(1)

[[ 4  0  8  0  0  0  0 11  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]]


In [8]:
from collections import defaultdict
import numpy as np

class Graph(): 

    def __init__(self, vertices): 
        self.V = vertices 
        self.graph = [] 
        self.graph_matrix = [[0 for column in range(vertices)]
                    for row in range(vertices)] 
    
    def addEdge(self,u,v,w): 
        """
        :type u,v,w: int
        :rtype: None
        """
    def Dijkstra(self, s):
        self.graph_matrix[0] = self.graph[s]
        path = [s] 
        visited = [False]*self.V 
        visited[s] = True
        temp = [] 
        visited = [False]
        for i in range(self.V):
            for j in range(self.V):
                if self.graph_matrix[i][j] != 0 and visited[j] == False:
                    temp.append(self.graph_matrix[i][j])
            path.append(self.graph_matrix[i].index(min(temp)))
            visited[path[-1]] = True
            
            self.graph_matrix[i+1] = self.graph_matrix[i]
            for k in range(self.V):
                if k == path[0]:
                    self.graph[i+1][k] = self.graph[i+1][k]
                if  
    
        print(np.matrix(self.graph_matrix))
        
    def Kruskal(self):
        """
        :rtype: dict
        """

In [9]:
a = Graph(9)
a.graph =  [[0,4,0,0,0,0,0,8,0],
            [4,0,8,0,0,0,0,11,0],
            [0,8,0,7,0,4,0,0,2],
            [0,0,7,0,9,14,0,0,0],
            [0,0,0,9,0,10,0,0,0],
            [0,0,4,14,10,0,2,0,0],
            [0,0,0,0,0,2,0,1,6],
            [8,11,0,0,0,0,1,0,7],
            [0,0,2,0,0,0,6,7,0]]
a.Dijkstra(0)

[[ 4  0  8  0  0  0  0 11  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0]]


In [1]:
from collections import defaultdict
import numpy as np

class Graph(): 

    def __init__(self, vertices): 
        self.V = vertices 
        self.graph = [] 
        self.graph_matrix = [[0 for column in range(vertices)]
                    for row in range(vertices)] 
    
    def addEdge(self,u,v,w): 
        """
        :type u,v,w: int
        :rtype: None
        """
    def Dijkstra(self, s):
#         self.graph_matrix[0] = self.graph[s]
#         path = [s] 
#         visited = [False]*self.V 
#         visited[s] = True
#         temp = [] 
#         visited = [False]
#         for i in range(self.V):
#             for j in range(self.V):
#                 if self.graph_matrix[i][j] != 0 and visited[j] == False:
#                     temp.append(self.graph_matrix[i][j])
#             path.append(self.graph_matrix[i].index(min(temp)))
#             visited[path[-1]] = True
            
#             self.graph_matrix[i+1] = self.graph_matrix[i]
#             for k in range(self.V):
#                 if k == path[0]:
#                     self.graph[i+1][k] = self.graph[i+1][k]
#                 if
        visited = [s]
        cur_len = 0
        fin_ans = dict()
        tempora = None
        for i in range(self.V):
            fin_ans[i] = None
        fin_ans[s] = 0
        for i in range(self.V-1):
            for j in range(len(self.graph[visited[-1]])):
                if self.graph[visited[-1]][j] != 0 and j not in visited:
                    if not tempora:
                        tempora = [j,self.graph[visited[-1]][j]]
                    else:
                        if self.graph[visited[-1]][j] < tempora[-1]:
                            tempora = [j,self.graph[visited[-1]][j]]
            visited.append(tempora[0])
            cur_len += tempora[-1]
            fin_ans[tempora[0]] = cur_len
            print("visited=",visited)
            print("cur_len=",cur_len)
            print("tempora=",tempora)
            print("fin_ans=",fin_ans)
            tempora = None
        return fin_ans 
        
    def Kruskal(self):
        """
        :rtype: dict
        """

In [25]:
a = Graph(5)
a.graph =  [[0,6,0,1,0],
           [6,0,5,2,2],
           [0,5,0,0,5],
           [1,2,0,0,1],
           [0,2,5,1,0]]
a.Dijkstra(0)

visited= [0, 3]
cur_len= 1
tempora= [3, 1]
fin_ans= {0: 0, 1: None, 2: None, 3: 1, 4: None}
visited= [0, 3, 4]
cur_len= 2
tempora= [4, 1]
fin_ans= {0: 0, 1: None, 2: None, 3: 1, 4: 2}
visited= [0, 3, 4, 1]
cur_len= 4
tempora= [1, 2]
fin_ans= {0: 0, 1: 4, 2: None, 3: 1, 4: 2}
visited= [0, 3, 4, 1, 2]
cur_len= 9
tempora= [2, 5]
fin_ans= {0: 0, 1: 4, 2: 9, 3: 1, 4: 2}


{0: 0, 1: 4, 2: 9, 3: 1, 4: 2}

In [2]:
a = Graph(9)
a.graph =  [[0,4,0,0,0,0,0,8,0],
            [4,0,8,0,0,0,0,11,0],
            [0,8,0,7,0,4,0,0,2],
            [0,0,7,0,9,14,0,0,0],
            [0,0,0,9,0,10,0,0,0],
            [0,0,4,14,10,0,2,0,0],
            [0,0,0,0,0,2,0,1,6],
            [8,11,0,0,0,0,1,0,7],
            [0,0,2,0,0,0,6,7,0]]
a.Dijkstra(0)

visited= [0, 1]
cur_len= 4
tempora= [1, 4]
fin_ans= {0: 0, 1: 4, 2: None, 3: None, 4: None, 5: None, 6: None, 7: None, 8: None}
visited= [0, 1, 2]
cur_len= 12
tempora= [2, 8]
fin_ans= {0: 0, 1: 4, 2: 12, 3: None, 4: None, 5: None, 6: None, 7: None, 8: None}
visited= [0, 1, 2, 8]
cur_len= 14
tempora= [8, 2]
fin_ans= {0: 0, 1: 4, 2: 12, 3: None, 4: None, 5: None, 6: None, 7: None, 8: 14}
visited= [0, 1, 2, 8, 6]
cur_len= 20
tempora= [6, 6]
fin_ans= {0: 0, 1: 4, 2: 12, 3: None, 4: None, 5: None, 6: 20, 7: None, 8: 14}
visited= [0, 1, 2, 8, 6, 7]
cur_len= 21
tempora= [7, 1]
fin_ans= {0: 0, 1: 4, 2: 12, 3: None, 4: None, 5: None, 6: 20, 7: 21, 8: 14}


TypeError: 'NoneType' object is not subscriptable

In [1]:
from collections import defaultdict
import numpy as np

class Graph(): 

    def __init__(self, vertices): 
        self.V = vertices 
        self.graph = [] 
        self.graph_matrix = [[0 for column in range(vertices)]
                    for row in range(vertices)] 
    
    def addEdge(self,u,v,w): 
        """
        :type u,v,w: int
        :rtype: None
        """
    def Dijkstra(self, s):
        visited = [s]
        final = dict()
        parent = dict()
        temp = []
        for i in range(self.V):
            final[i] = None
            parent[i] = None
        final[s] = 0
        for i in range(self.V-1):
            for j in range(len(self.graph[visited[-1]])):
                if self.graph[visited[-1]][j] != 0 and j not in visited:
                    
                    val = self.graph[visited[-1]][j] + final[visited[-1]]
                    
                    if not final[j]:
                        final[j] = val
                        parent[j] = visited[-1]
                    else:
                        if val < final[j]:
                            final[j] = val
                            parent[j] = visited[-1]
                    
                    if not temp:
                        temp.append([j,final[j]])
                    else:
                        det = True
                        for k in range(len(temp)):
                            if temp[k][1] > final[j]:
                                temp.insert(k,[j,final[j]])
                                det = False
                                break
                        if det:
                            temp.append([j,final[j]])
            
            while temp[0][0] in visited:
                temp.pop(0)
            visited.append(temp[0][0])
            temp.pop(0)
        print("final=",final)
        print("parent=",parent)

        return final 
        
    def Kruskal(self):
        """
        :rtype: dict
        """

In [2]:
a = Graph(9)
a.graph =  [[0,4,0,0,0,0,0,8,0],
            [4,0,8,0,0,0,0,11,0],
            [0,8,0,7,0,4,0,0,2],
            [0,0,7,0,9,14,0,0,0],
            [0,0,0,9,0,10,0,0,0],
            [0,0,4,14,10,0,2,0,0],
            [0,0,0,0,0,2,0,1,6],
            [8,11,0,0,0,0,1,0,7],
            [0,0,2,0,0,0,6,7,0]]
a.Dijkstra(2)

i= 0
visited= [2, 8]
final= {0: None, 1: 8, 2: 0, 3: 7, 4: None, 5: 4, 6: None, 7: None, 8: 2}
parent= {0: None, 1: 2, 2: None, 3: 2, 4: None, 5: 2, 6: None, 7: None, 8: 2}
i= 1
visited= [2, 8, 5]
final= {0: None, 1: 8, 2: 0, 3: 7, 4: None, 5: 4, 6: 8, 7: 9, 8: 2}
parent= {0: None, 1: 2, 2: None, 3: 2, 4: None, 5: 2, 6: 8, 7: 8, 8: 2}
i= 2
visited= [2, 8, 5, 6]
final= {0: None, 1: 8, 2: 0, 3: 7, 4: 14, 5: 4, 6: 6, 7: 9, 8: 2}
parent= {0: None, 1: 2, 2: None, 3: 2, 4: 5, 5: 2, 6: 5, 7: 8, 8: 2}
i= 3
visited= [2, 8, 5, 6, 3]
final= {0: None, 1: 8, 2: 0, 3: 7, 4: 14, 5: 4, 6: 6, 7: 7, 8: 2}
parent= {0: None, 1: 2, 2: None, 3: 2, 4: 5, 5: 2, 6: 5, 7: 6, 8: 2}
i= 4
visited= [2, 8, 5, 6, 3, 7]
final= {0: None, 1: 8, 2: 0, 3: 7, 4: 14, 5: 4, 6: 6, 7: 7, 8: 2}
parent= {0: None, 1: 2, 2: None, 3: 2, 4: 5, 5: 2, 6: 5, 7: 6, 8: 2}
i= 5
visited= [2, 8, 5, 6, 3, 7, 1]
final= {0: 15, 1: 8, 2: 0, 3: 7, 4: 14, 5: 4, 6: 6, 7: 7, 8: 2}
parent= {0: 7, 1: 2, 2: None, 3: 2, 4: 5, 5: 2, 6: 5, 7: 6, 8: 2}
i=

{0: 12, 1: 8, 2: 0, 3: 7, 4: 14, 5: 4, 6: 6, 7: 7, 8: 2}

In [3]:
a = Graph(9)
a.graph =  [[0,4,0,0,0,0,0,8,0],
            [4,0,8,0,0,0,0,11,0],
            [0,8,0,7,0,4,0,0,2],
            [0,0,7,0,9,14,0,0,0],
            [0,0,0,9,0,10,0,0,0],
            [0,0,4,14,10,0,2,0,0],
            [0,0,0,0,0,2,0,1,6],
            [8,11,0,0,0,0,1,0,7],
            [0,0,2,0,0,0,6,7,0]]
a.Dijkstra(1)

i= 0
visited= [1, 0]
final= {0: 4, 1: 0, 2: 8, 3: None, 4: None, 5: None, 6: None, 7: 11, 8: None}
parent= {0: 1, 1: None, 2: 1, 3: None, 4: None, 5: None, 6: None, 7: 1, 8: None}
i= 1
visited= [1, 0, 2]
final= {0: 4, 1: 0, 2: 8, 3: None, 4: None, 5: None, 6: None, 7: 11, 8: None}
parent= {0: 1, 1: None, 2: 1, 3: None, 4: None, 5: None, 6: None, 7: 1, 8: None}
i= 2
visited= [1, 0, 2, 8]
final= {0: 4, 1: 0, 2: 8, 3: 15, 4: None, 5: 12, 6: None, 7: 11, 8: 10}
parent= {0: 1, 1: None, 2: 1, 3: 2, 4: None, 5: 2, 6: None, 7: 1, 8: 2}
i= 3
visited= [1, 0, 2, 8, 7]
final= {0: 4, 1: 0, 2: 8, 3: 15, 4: None, 5: 12, 6: 16, 7: 11, 8: 10}
parent= {0: 1, 1: None, 2: 1, 3: 2, 4: None, 5: 2, 6: 8, 7: 1, 8: 2}
i= 4
visited= [1, 0, 2, 8, 7, 5]
final= {0: 4, 1: 0, 2: 8, 3: 15, 4: None, 5: 12, 6: 12, 7: 11, 8: 10}
parent= {0: 1, 1: None, 2: 1, 3: 2, 4: None, 5: 2, 6: 7, 7: 1, 8: 2}
i= 5
visited= [1, 0, 2, 8, 7, 5, 6]
final= {0: 4, 1: 0, 2: 8, 3: 15, 4: 22, 5: 12, 6: 12, 7: 11, 8: 10}
parent= {0: 1, 1: Non

{0: 4, 1: 0, 2: 8, 3: 15, 4: 22, 5: 12, 6: 12, 7: 11, 8: 10}

In [4]:
a = Graph(9)
a.graph =  [[0,4,0,0,0,0,0,8,0],
            [4,0,8,0,0,0,0,11,0],
            [0,8,0,7,0,4,0,0,2],
            [0,0,7,0,9,14,0,0,0],
            [0,0,0,9,0,10,0,0,0],
            [0,0,4,14,10,0,2,0,0],
            [0,0,0,0,0,2,0,1,6],
            [8,11,0,0,0,0,1,0,7],
            [0,0,2,0,0,0,6,7,0]]
a.Dijkstra(0)

i= 0
visited= [0, 1]
final= {0: 0, 1: 4, 2: None, 3: None, 4: None, 5: None, 6: None, 7: 8, 8: None}
parent= {0: None, 1: 0, 2: None, 3: None, 4: None, 5: None, 6: None, 7: 0, 8: None}
i= 1
visited= [0, 1, 7]
final= {0: 0, 1: 4, 2: 12, 3: None, 4: None, 5: None, 6: None, 7: 8, 8: None}
parent= {0: None, 1: 0, 2: 1, 3: None, 4: None, 5: None, 6: None, 7: 0, 8: None}
i= 2
visited= [0, 1, 7, 6]
final= {0: 0, 1: 4, 2: 12, 3: None, 4: None, 5: None, 6: 9, 7: 8, 8: 15}
parent= {0: None, 1: 0, 2: 1, 3: None, 4: None, 5: None, 6: 7, 7: 0, 8: 7}
i= 3
visited= [0, 1, 7, 6, 5]
final= {0: 0, 1: 4, 2: 12, 3: None, 4: None, 5: 11, 6: 9, 7: 8, 8: 15}
parent= {0: None, 1: 0, 2: 1, 3: None, 4: None, 5: 6, 6: 7, 7: 0, 8: 7}
i= 4
visited= [0, 1, 7, 6, 5, 2]
final= {0: 0, 1: 4, 2: 12, 3: 25, 4: 21, 5: 11, 6: 9, 7: 8, 8: 15}
parent= {0: None, 1: 0, 2: 1, 3: 5, 4: 5, 5: 6, 6: 7, 7: 0, 8: 7}
i= 5
visited= [0, 1, 7, 6, 5, 2, 8]
final= {0: 0, 1: 4, 2: 12, 3: 19, 4: 21, 5: 11, 6: 9, 7: 8, 8: 14}
parent= {0: Non

{0: 0, 1: 4, 2: 12, 3: 19, 4: 21, 5: 11, 6: 9, 7: 8, 8: 14}

In [2]:
a = Graph(9)
a.graph =  [[0,4,0,0,0,0,0,8,0],
            [4,0,8,0,0,0,0,11,0],
            [0,8,0,7,0,4,0,0,2],
            [0,0,7,0,9,14,0,0,0],
            [0,0,0,9,0,10,0,0,0],
            [0,0,4,14,10,0,2,0,0],
            [0,0,0,0,0,2,0,1,6],
            [8,11,0,0,0,0,1,0,7],
            [0,0,2,0,0,0,6,7,0]]
a.Dijkstra(3)

i= 0
visited= [3, 2]
final= {0: None, 1: None, 2: 7, 3: 0, 4: 9, 5: 14, 6: None, 7: None, 8: None}
parent= {0: None, 1: None, 2: 3, 3: None, 4: 3, 5: 3, 6: None, 7: None, 8: None}
i= 1
visited= [3, 2, 4]
final= {0: None, 1: 15, 2: 7, 3: 0, 4: 9, 5: 11, 6: None, 7: None, 8: 9}
parent= {0: None, 1: 2, 2: 3, 3: None, 4: 3, 5: 2, 6: None, 7: None, 8: 2}
i= 2
visited= [3, 2, 4, 8]
final= {0: None, 1: 15, 2: 7, 3: 0, 4: 9, 5: 11, 6: None, 7: None, 8: 9}
parent= {0: None, 1: 2, 2: 3, 3: None, 4: 3, 5: 2, 6: None, 7: None, 8: 2}
i= 3
visited= [3, 2, 4, 8, 5]
final= {0: None, 1: 15, 2: 7, 3: 0, 4: 9, 5: 11, 6: 15, 7: 16, 8: 9}
parent= {0: None, 1: 2, 2: 3, 3: None, 4: 3, 5: 2, 6: 8, 7: 8, 8: 2}
i= 4
visited= [3, 2, 4, 8, 5, 6]
final= {0: None, 1: 15, 2: 7, 3: 0, 4: 9, 5: 11, 6: 13, 7: 16, 8: 9}
parent= {0: None, 1: 2, 2: 3, 3: None, 4: 3, 5: 2, 6: 5, 7: 8, 8: 2}
i= 5
visited= [3, 2, 4, 8, 5, 6, 7]
final= {0: None, 1: 15, 2: 7, 3: 0, 4: 9, 5: 11, 6: 13, 7: 14, 8: 9}
parent= {0: None, 1: 2, 2: 3,

{0: 19, 1: 15, 2: 7, 3: 0, 4: 9, 5: 11, 6: 13, 7: 14, 8: 9}

In [2]:
a = Graph(9)
a.graph =  [[0,4,0,0,0,0,0,8,0],
            [4,0,8,0,0,0,0,11,0],
            [0,8,0,7,0,4,0,0,2],
            [0,0,7,0,9,14,0,0,0],
            [0,0,0,9,0,10,0,0,0],
            [0,0,4,14,10,0,2,0,0],
            [0,0,0,0,0,2,0,1,6],
            [8,11,0,0,0,0,1,0,7],
            [0,0,2,0,0,0,6,7,0]]
a.Dijkstra(4)

final= {0: 21, 1: 22, 2: 14, 3: 9, 4: 0, 5: 10, 6: 12, 7: 13, 8: 16}
parent= {0: 7, 1: 2, 2: 5, 3: 4, 4: None, 5: 4, 6: 5, 7: 6, 8: 2}


{0: 21, 1: 22, 2: 14, 3: 9, 4: 0, 5: 10, 6: 12, 7: 13, 8: 16}

In [2]:
a = Graph(9)
a.graph =  [[0,4,0,0,0,0,0,8,0],
            [4,0,8,0,0,0,0,11,0],
            [0,8,0,7,0,4,0,0,2],
            [0,0,7,0,9,14,0,0,0],
            [0,0,0,9,0,10,0,0,0],
            [0,0,4,14,10,0,2,0,0],
            [0,0,0,0,0,2,0,1,6],
            [8,11,0,0,0,0,1,0,7],
            [0,0,2,0,0,0,6,7,0]]
a.Dijkstra(5)

final= {0: 11, 1: 12, 2: 4, 3: 11, 4: 10, 5: 0, 6: 2, 7: 3, 8: 6}
parent= {0: 7, 1: 2, 2: 5, 3: 2, 4: 5, 5: None, 6: 5, 7: 6, 8: 2}


{0: 11, 1: 12, 2: 4, 3: 11, 4: 10, 5: 0, 6: 2, 7: 3, 8: 6}

In [2]:
a = Graph(9)
a.graph =  [[0,4,0,0,0,0,0,8,0],
            [4,0,8,0,0,0,0,11,0],
            [0,8,0,7,0,4,0,0,2],
            [0,0,7,0,9,14,0,0,0],
            [0,0,0,9,0,10,0,0,0],
            [0,0,4,14,10,0,2,0,0],
            [0,0,0,0,0,2,0,1,6],
            [8,11,0,0,0,0,1,0,7],
            [0,0,2,0,0,0,6,7,0]]
a.Dijkstra(6)

final= {0: 9, 1: 12, 2: 6, 3: 13, 4: 12, 5: 2, 6: 0, 7: 1, 8: 6}
parent= {0: 7, 1: 7, 2: 5, 3: 2, 4: 5, 5: 6, 6: None, 7: 6, 8: 6}


{0: 9, 1: 12, 2: 6, 3: 13, 4: 12, 5: 2, 6: 0, 7: 1, 8: 6}

In [3]:
a = Graph(9)
a.graph =  [[0,4,0,0,0,0,0,8,0],
            [4,0,8,0,0,0,0,11,0],
            [0,8,0,7,0,4,0,0,2],
            [0,0,7,0,9,14,0,0,0],
            [0,0,0,9,0,10,0,0,0],
            [0,0,4,14,10,0,2,0,0],
            [0,0,0,0,0,2,0,1,6],
            [8,11,0,0,0,0,1,0,7],
            [0,0,2,0,0,0,6,7,0]]
a.Dijkstra(7)

final= {0: 8, 1: 11, 2: 7, 3: 14, 4: 13, 5: 3, 6: 1, 7: 0, 8: 7}
parent= {0: 7, 1: 7, 2: 5, 3: 2, 4: 5, 5: 6, 6: 7, 7: None, 8: 7}


{0: 8, 1: 11, 2: 7, 3: 14, 4: 13, 5: 3, 6: 1, 7: 0, 8: 7}

In [4]:
a = Graph(9)
a.graph =  [[0,4,0,0,0,0,0,8,0],
            [4,0,8,0,0,0,0,11,0],
            [0,8,0,7,0,4,0,0,2],
            [0,0,7,0,9,14,0,0,0],
            [0,0,0,9,0,10,0,0,0],
            [0,0,4,14,10,0,2,0,0],
            [0,0,0,0,0,2,0,1,6],
            [8,11,0,0,0,0,1,0,7],
            [0,0,2,0,0,0,6,7,0]]
a.Dijkstra(8)

final= {0: 14, 1: 10, 2: 2, 3: 9, 4: 16, 5: 6, 6: 6, 7: 7, 8: 0}
parent= {0: 1, 1: 2, 2: 8, 3: 2, 4: 5, 5: 2, 6: 8, 7: 8, 8: None}


{0: 14, 1: 10, 2: 2, 3: 9, 4: 16, 5: 6, 6: 6, 7: 7, 8: 0}

In [10]:
fin_ans = dict() #這邊先測試創建一個dict
for i in range(9):
    fin_ans[i] = None
print(fin_ans)

{0: None, 1: None, 2: None, 3: None, 4: None, 5: None, 6: None, 7: None, 8: None}


In [16]:
temp = [] #測試 if not temp 跟 if len(temp) == 0的效果 是否相同
if not temp:
    print("imucici")
temp.append([1,6])
if temp:
    print("haha")

imucici
haha


In [12]:
None + 3 # None跟3無法相加

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [5]:
a = [[2,8]] # 測試insert函式
a.insert(0,[7,3])
print(a)

[[7, 3], [2, 8]]


最小生成樹的步驟

1.Sort all the edges in non-decreasing order of their weight.

2.Pick the smallest edge. Check if it forms a cycle with the spanning tree formed so far.If cycle is not formed, include this edge. Else, discard it.

3.Repeat step#2 until there are (V-1) edges in the spanning tree.

In [ ]:
from collections import defaultdict

class Graph(): 

    def __init__(self, vertices): 
        self.V = vertices 
        self.graph = [] 
        self.graph_matrix = [[0 for column in range(vertices)]
                    for row in range(vertices)] 
    
    def addEdge(self,u,v,w): 
        """
        :type u,v,w: int
        :rtype: None
        """
        
    def Kruskal(self):
        

In [14]:
from collections import defaultdict
import numpy as np

class Graph(): 

    def __init__(self, vertices): 
        self.V = vertices 
        self.graph = [] 
        self.graph_matrix = [[0 for column in range(vertices)]
                    for row in range(vertices)] 
    
    def addEdge(self,u,v,w): 
        """
        :type u,v,w: int
        :rtype: None
        """
    def Dijkstra(self, s):
        visited = [s]
        final = dict()
        parent = dict()
        temp = []
        for i in range(self.V):
            final[i] = None
            parent[i] = None
        final[s] = 0
        for i in range(self.V-1):
            for j in range(len(self.graph[visited[-1]])):
                if self.graph[visited[-1]][j] != 0 and j not in visited:
                    
                    val = self.graph[visited[-1]][j] + final[visited[-1]]
                    
                    if not final[j]:
                        final[j] = val
                        parent[j] = visited[-1]
                    else:
                        if val < final[j]:
                            final[j] = val
                            parent[j] = visited[-1]
                    
                    if not temp:
                        temp.append([j,final[j]])
                    else:
                        det = True
                        for k in range(len(temp)):
                            if temp[k][1] > final[j]:
                                temp.insert(k,[j,final[j]])
                                det = False
                                break
                        if det:
                            temp.append([j,final[j]])
            
            while temp[0][0] in visited:
                temp.pop(0)
            visited.append(temp[0][0])
            temp.pop(0)
        print("final=",final)
        print("parent=",parent)
        
        last = {}
        for i in range(self.V):
            last[str(i)] = final[i]

        return last
        
    def Kruskal(self):
        """
        :rtype: dict
        """

In [15]:
a = Graph(9)
a.graph =  [[0,4,0,0,0,0,0,8,0],
            [4,0,8,0,0,0,0,11,0],
            [0,8,0,7,0,4,0,0,2],
            [0,0,7,0,9,14,0,0,0],
            [0,0,0,9,0,10,0,0,0],
            [0,0,4,14,10,0,2,0,0],
            [0,0,0,0,0,2,0,1,6],
            [8,11,0,0,0,0,1,0,7],
            [0,0,2,0,0,0,6,7,0]]
a.Dijkstra(8)

final= {0: 14, 1: 10, 2: 2, 3: 9, 4: 16, 5: 6, 6: 6, 7: 7, 8: 0}
parent= {0: 1, 1: 2, 2: 8, 3: 2, 4: 5, 5: 2, 6: 8, 7: 8, 8: None}


{'0': 14, '1': 10, '2': 2, '3': 9, '4': 16, '5': 6, '6': 6, '7': 7, '8': 0}

In [16]:
a = {}
a["0"] = 1
print(a)

{'0': 1}


In [26]:
a = 2
b = 3
c = str(str(a)+"-"+str(b))
d = {}
d[c] = "I hate 司ㄈㄇ"
print(d)

{'2-3': 'I hate 司ㄈㄇ'}


In [1]:
from collections import defaultdict

class Graph(): 

    def __init__(self, vertices): 
        self.V = vertices 
        self.graph = [] 
        self.array = []
        self.visit = {}
    
    def addEdge(self,u,v,w): 
        self.array.append([u,v,w])

    def K_helper(self,final):
        
        pivot = []
        for i in range(len(self.array)):
            edge1,edge2,costs = self.array[i][0],self.array[i][1],self.array[i][2]
            if not (self.visit[edge1] and self.visit[edge2]):
                if not pivot or costs < pivot[2]:
                    pivot = self.array[i]
        
        self.array.remove(pivot)
        
        for edge in range(2):
            if not self.visit[pivot[edge]]:
                self.visit[pivot[edge]] = True
  
        final[str(str(pivot[0])+"-"+str(pivot[1]))] = pivot[2]

        for check in range(len(self.visit)):
            if not self.visit[check]:
                self.K_helper(final)
        
        return final
    
    def Kruskal(self):
        for j in range(self.V): 
            self.visit[j] = False
        final = {}
        return self.K_helper(final)

In [2]:
g = Graph(4)
g.addEdge(0,1,10)
g.addEdge(0,2,6)
g.addEdge(0,3,5)
g.addEdge(1,3,15)
g.addEdge(2,3,4)
g.Kruskal()

{'2-3': 4, '0-3': 5, '0-1': 10}

In [2]:
g = Graph(9)
g.addEdge(0,1,4)
g.addEdge(0,7,8)
g.addEdge(1,7,11)
g.addEdge(1,2,8)
g.addEdge(7,8,7)
g.addEdge(7,6,1)
g.addEdge(2,8,2)
g.addEdge(8,6,6)
g.addEdge(2,3,7)
g.addEdge(2,5,4)
g.addEdge(6,5,2)
g.addEdge(3,5,14)
g.addEdge(4,3,9)
g.addEdge(5,4,10)
g.Kruskal()

{'7-6': 1, '2-8': 2, '6-5': 2, '0-1': 4, '2-3': 7, '4-3': 9}

今天我不能用 "是否每個點都走過了" 來當作我的程式碼 "是否該停止" 的判斷式

因為有可能 "每個點都走過了" 但彼此不會連成一條路徑

In [1]:
from collections import defaultdict

class Graph(): 

    def __init__(self, vertices): 
        self.V = vertices 
        self.graph = [] 
        self.array = []
        self.visit = {}
    
    def addEdge(self,u,v,w): 
        self.array.append([u,v,w])

    def K_helper(self,final):
        
        pivot = []
        cur = len(self.array)-1
        for i in range(len(self.array)):
            edge1,edge2,costs = self.array[i][0],self.array[i][1],self.array[i][2]
            if self.visit[edge1] and self.visit[edge2]:
                self.array.pop(i)
                cur = cur - 1
            else:
                if not (self.visit[edge1] and self.visit[edge2]):
                    if not pivot or costs < pivot[2]:
                        pivot = self.array[i]
            if i == cur:
                break
        print("pivot=",pivot)
        print("self.array=",self.array)
        print()
        
        if pivot:
            self.array.remove(pivot)
        
            for edge in range(2):
                if not self.visit[pivot[edge]]:
                    self.visit[pivot[edge]] = True

            final[str(str(pivot[0])+"-"+str(pivot[1]))] = pivot[2]

        if len(final) != self.V-1:
            self.K_helper(final)
        
        return final
    
    def Kruskal(self):
        for j in range(self.V): 
            self.visit[j] = False
        final = {}
        return self.K_helper(final)

In [2]:
g = Graph(9)
g.addEdge(0,1,4)
g.addEdge(0,7,8)
g.addEdge(1,7,11)
g.addEdge(1,2,8)
g.addEdge(7,8,7)
g.addEdge(7,6,1)
g.addEdge(2,8,2)
g.addEdge(8,6,6)
g.addEdge(2,3,7)
g.addEdge(2,5,4)
g.addEdge(6,5,2)
g.addEdge(3,5,14)
g.addEdge(3,4,9)
g.addEdge(5,4,10)
g.Kruskal()

pivot= [7, 6, 1]
self.array= [[0, 1, 4], [0, 7, 8], [1, 7, 11], [1, 2, 8], [7, 8, 7], [7, 6, 1], [2, 8, 2], [8, 6, 6], [2, 3, 7], [2, 5, 4], [6, 5, 2], [3, 5, 14], [3, 4, 9], [5, 4, 10]]

pivot= [2, 8, 2]
self.array= [[0, 1, 4], [0, 7, 8], [1, 7, 11], [1, 2, 8], [7, 8, 7], [2, 8, 2], [8, 6, 6], [2, 3, 7], [2, 5, 4], [6, 5, 2], [3, 5, 14], [3, 4, 9], [5, 4, 10]]

pivot= [6, 5, 2]
self.array= [[0, 1, 4], [0, 7, 8], [1, 7, 11], [1, 2, 8], [8, 6, 6], [2, 3, 7], [2, 5, 4], [6, 5, 2], [3, 5, 14], [3, 4, 9], [5, 4, 10]]

pivot= [0, 1, 4]
self.array= [[0, 1, 4], [0, 7, 8], [1, 7, 11], [1, 2, 8], [2, 3, 7], [3, 5, 14], [3, 4, 9], [5, 4, 10]]

pivot= [3, 4, 9]
self.array= [[1, 7, 11], [2, 3, 7], [3, 5, 14], [3, 4, 9], [5, 4, 10]]

pivot= []
self.array= [[2, 3, 7], [5, 4, 10]]

pivot= []
self.array= [[5, 4, 10]]

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivo

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
se

self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= 

self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= 

self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= 

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
se

self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= 

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
self.array= []

pivot= []
se

RecursionError: maximum recursion depth exceeded while calling a Python object

所以只單純紀錄visited還不夠嚴謹，還要確定說484有形成loop

In [1]:
from collections import defaultdict

class Graph(): 

    def __init__(self, vertices): 
        self.V = vertices 
        self.graph = [] 
        self.array = []
        self.roots = {}
    
    def addEdge(self,u,v,w): 
        if not self.array:
            self.array.append([u,v,w])
        else:
            det = True
            for i in range(len(self.array)):
                if self.array[i][2] > w:
                    self.array.insert(i,[u,v,w])
                    det = False
                    break
            if det:
                self.array.append([u,v,w])

    def K_helper(self,final):
        
        pivot = self.array[0]

        while self.roots[pivot[0]] != None and self.roots[pivot[1]] != None and self.roots[pivot[0]] == self.roots[pivot[1]]:
            self.array.pop(0)
            pivot = self.array[0]
        
        print("pivot=",pivot)
        print("self.array=",self.array)
        
        self.array.remove(pivot)
        
        small = min(pivot[0],pivot[1])
        large = max(pivot[0],pivot[1])

        if self.roots[large] == None and self.roots[small] == None:
            self.roots[large] , self.roots[small] = small , small

        elif self.roots[large] == None and self.roots[small] != None:
            self.roots[large] = self.roots[small]          

        else:
            for i in range(self.V):
                if i != large and self.roots[i] == self.roots[large]:
                    self.roots[i] = small
            self.roots[large] , self.roots[small] = small , small
        
            

        final[str(str(pivot[0])+"-"+str(pivot[1]))] = pivot[2]
        print("final=",final)
        print("self.roots=",self.roots)
        print()

        if len(final) != self.V-1:
            self.K_helper(final)
        
        return final
    
    def Kruskal(self):
        for j in range(self.V): 
            self.roots[j] = None
        final = {}
        return self.K_helper(final)

In [2]:
g = Graph(9)
g.addEdge(0,1,4)
g.addEdge(0,7,8)
g.addEdge(1,7,11)
g.addEdge(1,2,8)
g.addEdge(7,8,7)
g.addEdge(7,6,1)
g.addEdge(2,8,2)
g.addEdge(8,6,6)
g.addEdge(2,3,7)
g.addEdge(2,5,4)
g.addEdge(6,5,2)
g.addEdge(3,5,14)
g.addEdge(3,4,9)
g.addEdge(5,4,10)
g.Kruskal()

pivot= [7, 6, 1]
self.array= [[7, 6, 1], [2, 8, 2], [6, 5, 2], [0, 1, 4], [2, 5, 4], [8, 6, 6], [7, 8, 7], [2, 3, 7], [0, 7, 8], [1, 2, 8], [3, 4, 9], [5, 4, 10], [1, 7, 11], [3, 5, 14]]
final= {'7-6': 1}
self.roots= {0: None, 1: None, 2: None, 3: None, 4: None, 5: None, 6: 6, 7: 6, 8: None}

pivot= [2, 8, 2]
self.array= [[2, 8, 2], [6, 5, 2], [0, 1, 4], [2, 5, 4], [8, 6, 6], [7, 8, 7], [2, 3, 7], [0, 7, 8], [1, 2, 8], [3, 4, 9], [5, 4, 10], [1, 7, 11], [3, 5, 14]]
final= {'7-6': 1, '2-8': 2}
self.roots= {0: None, 1: None, 2: 2, 3: None, 4: None, 5: None, 6: 6, 7: 6, 8: 2}

pivot= [6, 5, 2]
self.array= [[6, 5, 2], [0, 1, 4], [2, 5, 4], [8, 6, 6], [7, 8, 7], [2, 3, 7], [0, 7, 8], [1, 2, 8], [3, 4, 9], [5, 4, 10], [1, 7, 11], [3, 5, 14]]
final= {'7-6': 1, '2-8': 2, '6-5': 2}
self.roots= {0: None, 1: None, 2: 2, 3: None, 4: None, 5: 5, 6: 5, 7: 5, 8: 2}

pivot= [0, 1, 4]
self.array= [[0, 1, 4], [2, 5, 4], [8, 6, 6], [7, 8, 7], [2, 3, 7], [0, 7, 8], [1, 2, 8], [3, 4, 9], [5, 4, 10], [1, 7,

{'7-6': 1,
 '2-8': 2,
 '6-5': 2,
 '0-1': 4,
 '2-5': 4,
 '2-3': 7,
 '0-7': 8,
 '3-4': 9}

12/26整整花了一天的時間來寫==目前算是答案有出來了，但只測一組還是不夠嚴謹

In [3]:
g = Graph(7)
g.addEdge(0,5,3)
g.addEdge(0,1,5)
g.addEdge(5,4,6)
g.addEdge(1,4,1)
g.addEdge(1,2,10)
g.addEdge(1,6,4)
g.addEdge(4,6,2)
g.addEdge(4,3,7)
g.addEdge(6,2,8)
g.addEdge(6,3,9)
g.addEdge(2,3,5)
g.Kruskal()

pivot= [1, 4, 1]
self.array= [[1, 4, 1], [4, 6, 2], [0, 5, 3], [1, 6, 4], [0, 1, 5], [2, 3, 5], [5, 4, 6], [4, 3, 7], [6, 2, 8], [6, 3, 9], [1, 2, 10]]
final= {'1-4': 1}
self.roots= {0: None, 1: 1, 2: None, 3: None, 4: 1, 5: None, 6: None}

pivot= [4, 6, 2]
self.array= [[4, 6, 2], [0, 5, 3], [1, 6, 4], [0, 1, 5], [2, 3, 5], [5, 4, 6], [4, 3, 7], [6, 2, 8], [6, 3, 9], [1, 2, 10]]
final= {'1-4': 1, '4-6': 2}
self.roots= {0: None, 1: 1, 2: None, 3: None, 4: 1, 5: None, 6: 1}

pivot= [0, 5, 3]
self.array= [[0, 5, 3], [1, 6, 4], [0, 1, 5], [2, 3, 5], [5, 4, 6], [4, 3, 7], [6, 2, 8], [6, 3, 9], [1, 2, 10]]
final= {'1-4': 1, '4-6': 2, '0-5': 3}
self.roots= {0: 0, 1: 1, 2: None, 3: None, 4: 1, 5: 0, 6: 1}

pivot= [0, 1, 5]
self.array= [[0, 1, 5], [2, 3, 5], [5, 4, 6], [4, 3, 7], [6, 2, 8], [6, 3, 9], [1, 2, 10]]
final= {'1-4': 1, '4-6': 2, '0-5': 3, '0-1': 5}
self.roots= {0: 0, 1: 0, 2: None, 3: None, 4: 0, 5: 0, 6: 0}

pivot= [2, 3, 5]
self.array= [[2, 3, 5], [5, 4, 6], [4, 3, 7], [6, 2, 8], 

{'1-4': 1, '4-6': 2, '0-5': 3, '0-1': 5, '2-3': 5, '4-3': 7}

In [2]:
g = Graph(7)
g.addEdge(0,1,30)
g.addEdge(0,2,14)
g.addEdge(1,2,19)
g.addEdge(2,3,12)
g.addEdge(1,5,20)
g.addEdge(3,4,32)
g.addEdge(4,5,26)
g.addEdge(4,6,18)
g.addEdge(5,6,28)
g.Kruskal()

pivot= [2, 3, 12]
self.array= [[2, 3, 12], [0, 2, 14], [4, 6, 18], [1, 2, 19], [1, 5, 20], [4, 5, 26], [5, 6, 28], [0, 1, 30], [3, 4, 32]]
final= {'2-3': 12}
self.roots= {0: None, 1: None, 2: 2, 3: 2, 4: None, 5: None, 6: None}

pivot= [0, 2, 14]
self.array= [[0, 2, 14], [4, 6, 18], [1, 2, 19], [1, 5, 20], [4, 5, 26], [5, 6, 28], [0, 1, 30], [3, 4, 32]]
final= {'2-3': 12, '0-2': 14}
self.roots= {0: 0, 1: None, 2: 0, 3: 0, 4: None, 5: None, 6: None}

pivot= [4, 6, 18]
self.array= [[4, 6, 18], [1, 2, 19], [1, 5, 20], [4, 5, 26], [5, 6, 28], [0, 1, 30], [3, 4, 32]]
final= {'2-3': 12, '0-2': 14, '4-6': 18}
self.roots= {0: 0, 1: None, 2: 0, 3: 0, 4: 4, 5: None, 6: 4}

pivot= [1, 2, 19]
self.array= [[1, 2, 19], [1, 5, 20], [4, 5, 26], [5, 6, 28], [0, 1, 30], [3, 4, 32]]
final= {'2-3': 12, '0-2': 14, '4-6': 18, '1-2': 19}
self.roots= {0: 1, 1: 1, 2: 1, 3: 1, 4: 4, 5: None, 6: 4}

pivot= [1, 5, 20]
self.array= [[1, 5, 20], [4, 5, 26], [5, 6, 28], [0, 1, 30], [3, 4, 32]]
final= {'2-3': 12, '0-2

{'2-3': 12, '0-2': 14, '4-6': 18, '1-2': 19, '1-5': 20, '4-5': 26}

In [5]:
from collections import defaultdict

class Graph(): 

    def __init__(self, vertices): 
        self.V = vertices 
        self.graph = [] 
        self.array = []
        self.roots = {}
    
    def addEdge(self,u,v,w): 
        if not self.array:
            self.array.append([u,v,w])
        else:
            det = True
            for i in range(len(self.array)):
                if self.array[i][2] > w:
                    self.array.insert(i,[u,v,w])
                    det = False
                    break
            if det:
                self.array.append([u,v,w])

    def K_helper(self,final):
        
        pivot = self.array[0]

        while self.roots[pivot[0]] != None and self.roots[pivot[1]] != None and self.roots[pivot[0]] == self.roots[pivot[1]]:
            self.array.pop(0)
            pivot = self.array[0]
        
        self.array.remove(pivot)
        
        small = min(pivot[0],pivot[1])
        large = max(pivot[0],pivot[1])

        if self.roots[large] == None and self.roots[small] == None:
            self.roots[large] , self.roots[small] = small , small

        elif self.roots[large] == None and self.roots[small] != None:
            self.roots[large] = self.roots[small]          

        else:
            for i in range(self.V):
                if i != large and self.roots[i] == self.roots[large]:
                    self.roots[i] = small
            self.roots[large] , self.roots[small] = small , small

        final[str(str(pivot[0])+"-"+str(pivot[1]))] = pivot[2]

        if len(final) != self.V-1:
            self.K_helper(final)
        
        return final
    
    def Kruskal(self):
        for j in range(self.V): 
            self.roots[j] = None
        final = {}
        return self.K_helper(final)
    
    def Dijkstra(self, s):
        visited = [s]
        final = dict()
        parent = dict()
        temp = []
        for i in range(self.V):
            final[i] = None
            parent[i] = None
        final[s] = 0
        for i in range(self.V-1):
            for j in range(len(self.graph[visited[-1]])):
                if self.graph[visited[-1]][j] != 0 and j not in visited:
                    
                    val = self.graph[visited[-1]][j] + final[visited[-1]]
                    
                    if not final[j]:
                        final[j] = val
                        parent[j] = visited[-1]
                    else:
                        if val < final[j]:
                            final[j] = val
                            parent[j] = visited[-1]
                    
                    if not temp:
                        temp.append([j,final[j]])
                    else:
                        det = True
                        for k in range(len(temp)):
                            if temp[k][1] > final[j]:
                                temp.insert(k,[j,final[j]])
                                det = False
                                break
                        if det:
                            temp.append([j,final[j]])
            
            while temp[0][0] in visited:
                temp.pop(0)
            visited.append(temp[0][0])
            temp.pop(0)
        
        last = {}
        for i in range(self.V):
            last[str(i)] = final[i]

        return last

In [27]:
visit = {} #測試dict
if not visit:
    print("imuhaha")

imuhaha


In [32]:
visit = {} #測試dict
visit[2] = False
if not visit[2]:
    print("haha")

haha


In [33]:
a,b,c,d = 1,2,3,4 #測試一次設多個變數
print(a,b,c,d) 

1 2 3 4


In [36]:
a = set() #測試set add 重複值不會add進去
a.add(1)
a.add(1)
print(a)
print(len(a))

{1}
1


In [37]:
visit = {} #測試dict有沒有len屬性
visit[2] = True
len(visit)

1

In [38]:
a = [2,3,4] #測試助教要求的return type格式
final = {}
final[str(str(a[0])+"-"+str(a[1]))] = a[2]
print(final)

{'2-3': 4}


In [3]:
a = None #測試 None 的判斷式
b = None
if b:
    print("haha")
else:
    print("no")

no


In [3]:
a = {} #測試dict的value可否更改
a[0] = 2
for i in range(len(a)):
    if a[i] == 2:
        a[i] = 3
print(a)

{0: 3}


In [5]:
a = {} #測試not用法
a[0] = None
a[1] = None
if not a[0] and not a[1]:
    print("haha")

haha


Dijkstra、Kruskal原理說明：

"最短路徑" 跟 "最小生成樹" 的差別在於

最短路徑，尋找的答案是，給定一個基準點，要算出 "所有其他點" 到 "基準點" 的 "最短距離"

最小生成樹，不需要給定基準點，而是會從權重(或是路徑)最小的path開始走訪，直到連成V-1條邊

=================

最短路徑的執行步驟

1.從基準點開始，向外延伸一格能到達的所有vertex，並且從那些vertex當中，選一條路徑最短的

2.再從剛剛選定的vertex向外延伸一格所有能到達的vertex，並且也是選一條路徑最短的

3.重複2.這個步驟，直到每個vertex都被拜訪過，那麼最終的答案就出來了

4.拜訪過的vertex就不會再重複拜訪了

5.需要紀錄每個vertex的 "上一個節點" 或者是說parent，以便回頭尋找最短路徑所經過的點

程式碼實現的部分

1.創建final跟parent兩個deictionary，長度為self.V，一開始都預設為None

2.創建visited，用來存放 "拜訪過的節點" ，創建temp，其概念為 "Priority Queue"

3.承上，其概念為，按照最短路徑 "從小到大" 來排序，假設0到1長度為4，0到7長度為8，那麼temp = [[1,4],[7,8]]

4.依照Queue的概念，每次都只能從頭取出，如此變成確保取出的皆為最短路徑，還要注意取出的點不能在visited裡面

==================

最小生成樹的執行步驟

1.先把所有path按照權重，從小到大排序

2.需要一個表格來記錄每個edge所屬的 "subset" 或稱 "子集合" 至於子集合要用哪個edge當作代表 可以自行訂定一套規則

3.每次都會從權重最小的path選一個，並且確認那兩個edge的subset不相同，才可以把這個path加入最小生成樹

4.重複執行3.這個步驟，直到有V-1個path都被加入最小生成樹，那就可以停止了

程式碼實現的部分

1.由於要防止loop，會有discard的情況產生，無法確定程式碼執行的次數，故需要使用recursive的寫法，所以分2個def

2.創建self.array、self.roots(子集合)，使用self.變數，就可以在整個class內部使用，比較方便也不用去思考error

3.助教輸入的u v w，我會先弄成[u,v,w]，再按照w由小到大排，放入self.array，有點類似 "Priority Queue" 的概念

4.我自行定義的self.roots規則為，如果今天[7 6 1]要進來，7跟6都沒有root的情況，此兩個點的root都會變成6(選小的)

5.再來[6 5 2]要進來的話，7 6 5的root都會變成5，所以代表要重新去看 "有誰的root跟6的root一樣，請改成5哦"

6.創建final這個dictionary，預設長度為0，每次成功的新增path到最小升成樹之後，final都會新增一次

7.當final的長度還沒達到V-1的時候，就會一直進行recursive，反之，則可以return final

8.每次從self.array取出的時候，一樣是用Queue的概念，while取出的 "兩個邊的roots相同，就刪除，重新取出"

In [2]:
from IPython.display import Image
from IPython.core.display import HTML
Image(url="https://github.com/samuel871211/My-python-code/blob/master/week6/d%20k%20%E6%B5%81%E7%A8%8B%E5%9C%96.jpg?raw=true"  ,width = 1000,height = 1000)